'use client'
import '../scss/index.scss';
import { Inter } from 'next/font/google'
import Providers from '../Providers/Providers'
import { ToastContainer } from 'react-toastify';
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  description: 'Generated by create next app',
  title: 'Fenrir Collectibles- Admin Panel',
  icons: {
    icon: '/icon.ico',
    apple: '/apple-icon.ico'
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}


